version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=knectimob@gmail.com
      - N8N_BASIC_AUTH_PASSWORD=148919713@Knct
    volumes:
      - ./n8n_data:/home/node/.n8n