name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou o branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.root }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/KNECTHub"
          rm: true

      - name: Run deploy script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.root }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/KNECTHub
            npm install -g pm2 ts-node typescript
            pm2 restart KNECTHub || pm2 start $(which ts-node) -- index.ts --name "KNECTHub"
